### ISSUE TITLE
Use @substrate/calc npm package for fee calculation

### ISSUE THREAD

**Issue by emostov** [TheGoldenEye/polka-store#1]
You might be able able to benefit from using this npm package that was launched last week: 
https://www.npmjs.com/package/@substrate/calc

Just replace this line with:
https://github.com/TheGoldenEye/polka-store/blob/bb1894dcfaacdf9fdcedafc29670e5b54281c3d9/src/ApiHandler.ts#L18
With:
https://github.com/paritytech/substrate-api-sidecar/blob/1158cb72acc7d67237af28b0f6f4280e825508a3/src/services/blocks/BlocksService.ts#L16

I think then you can just uncomment the code block starting here:
https://github.com/TheGoldenEye/polka-store/blob/bb1894dcfaacdf9fdcedafc29670e5b54281c3d9/src/ApiHandler.ts#L190

I haven't looked too closely at the current code in this repo so there might be some other stuff you need to do, but I think all the logic you need for fee calcs is in Sidecar's `BlocksService`.

**Comment by TheGoldenEye** [comment]
Thanks for information, zeke.
Some days ago I removed the calc-fee code from my project, because I got better results calculating the fee from the "balances.Deposit" and "treasury.Deposit" events.
Nevertheless, many thanks for providing the npm, maybe I will use it after all.
